[package]
name = "evolution-sim-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
naga = "0.14.2"
noise = "0.8.2"
rand = "0.8.5"

